# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://adamwkraft.github.io'
baseurl: ''
title: 'Adam Kraft'
description: ''
permalink: pretty
logo: "/assets/my_image.jpeg"

# Pagination
paginate: 15
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: Work Projects
  url: /work_projects/
- title: Personal Projects
  url: /personal_projects/
- title: Talks
  url: /talks/
#- title:Blog
#  url: /blog/

# Footer nav
navigation_footer:
  Home: /

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/adamwkraft
  LinkedIn: https://www.linkedin.com/in/adam-kraft-7555b534/
  GitHub: https://github.com/adamwkraft
  link: https://adawkraft.github.io

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  Twitter: "#0d94e7"
  # facebook: "#3B5998"
  # Google+: "#DC4E41"
  # Pinterest: "#BD081C"
  LinkedIn: "#0077B5"
  # tumblr: "#36465D"
  # Reddit: "#FF4500"
  # Hacker News: "#ff6600"
  # Designer News: "#2D72D9"
  # Email: ""

# Collections
collections:
  posts:
    title: Blog
    output: true

google_analytics: UA-140001981-1
